TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.1
  max_vel_theta: 0.5
  min_in_place_vel_theta: 0.1
  escape_vel: -0.2
  acc_lim_theta: 0.25
  acc_lim_x: 0.25
  acc_lim_y: 0.25
  sim_time: 4
  meter_scoring: true
  holonomic_robot: false


EBandPlannerROS:
  xy_goal_tolerance: 0.15 
  yaw_goal_tolerance: 0.13
  rot_stopped_vel: 0.05
  trans_stopped_vel: 0.05
  marker_lifetime: 20.0
  max_vel_lin: 0.75
  max_vel_th: 1.0
  min_vel_th: 0.5
  min_in_place_vel_th: 2.0
  k_prop: 1.0
  k_damp: 3.5
  Ctrl_Rate: 50
  max_translational_acceleration: 2.5
  max_rotational_acceleration: 1.5
  differential_drive: true
  max_acceleration: 2.5



TebLocalPlannerROS:
  teb_autosize: True
  dt_ref: 0.3
  dt_hysteresis: 0.03
  global_plan_overwrite_orientation: True
  max_global_plan_lookahead_dist: 1.0
  feasibility_check_no_poses: 1
  wheelbase: 0.0
  acc_lim_x: 0.25
  acc_lim_y: 0.25
  acc_lim_theta: 1.5
  footprint_model:
    type: "polygon"
    vertices: [[-0.4, -0.5], [-0.4, 0.5], [0.4, 0.5], [0.4, -0.5]]
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.1
  free_goal_vel: False
  min_obstacle_dist: 0.4
  include_costmap_obstacles: True
  costmap_obstacles_behind_robot_dist: 1.0
  obstacle_poses_affected: 10
  costmap_converter_spin_thread: True
  costmap_converter_rate: 5
  min_obstacle_dist: 0.35
  inflation_dist: 0.45
  dynamic_obstacle_inflation_dist: 0.6
  obstacle_association_force_inclusion_factor: 2.0
  obstacle_association_cutoff_factor: 4.0
