map_type: costmap

obstacle_range: 4.0
raytrace_range: 6.0

transform_tolerance: 0.8

#robot_radius: ir_of_robot
footprint: [[-0.4, -0.5], [-0.4, 0.5], [0.4, 0.5], [0.4, -0.5]] 
inflation_radius: 0.8

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /bresilla/laser/scan, marking: true, clearing: true}